apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-06-03T18:33:07Z"
  generation: 1
  name: webapp-food
  namespace: app-space
  resourceVersion: "2320"
  selfLink: /apis/apps/v1/namespaces/app-space/deployments/webapp-food
  uid: 7722ff5d-c737-4960-9a68-b96a722dbba6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp-food
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp-food
    spec:
      containers:
      - image: kodekloud/ecommerce:food
        imagePullPolicy: Always
        name: webapp-food
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-03T18:33:11Z"
    lastUpdateTime: "2020-06-03T18:33:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-06-03T18:33:07Z"
    lastUpdateTime: "2020-06-03T18:33:11Z"
    message: ReplicaSet "webapp-food-678778b595" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1