apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-05T09:47:46Z"
  name: default-http-backend
  namespace: app-space
  resourceVersion: "548"
  selfLink: /api/v1/namespaces/app-space/services/default-http-backend
  uid: 24892c83-076e-4226-853b-405eb6d2a01f
spec:
  clusterIP: 10.101.57.180
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: default-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}