apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-05T09:47:46Z"
  name: video-service
  namespace: app-space
  resourceVersion: "531"
  selfLink: /api/v1/namespaces/app-space/services/video-service
  uid: cccfea2c-dbd6-460b-8a90-28c64be1394a
spec:
  clusterIP: 10.107.234.43
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp-video
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}