apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-05T09:47:46Z"
  name: wear-service
  namespace: app-space
  resourceVersion: "514"
  selfLink: /api/v1/namespaces/app-space/services/wear-service
  uid: 988128a5-1621-4850-b2d0-d9039728b955
spec:
  clusterIP: 10.96.215.72
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp-wear
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}