apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-06-05T10:17:17Z"
  name: ingress-serviceaccount
  namespace: ingress-space
  resourceVersion: "2962"
  selfLink: /api/v1/namespaces/ingress-space/serviceaccounts/ingress-serviceaccount
  uid: d9371198-0884-4262-a601-a22216a15054
secrets:
- name: ingress-serviceaccount-token-gq6xn