apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-03T18:14:43Z"
  name: default-http-backend
  namespace: app-space
  resourceVersion: "600"
  selfLink: /api/v1/namespaces/app-space/services/default-http-backend
  uid: f55225a8-4aa6-4cce-8840-22621697a4c8
spec:
  clusterIP: 10.101.73.52
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: default-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}