apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-03T18:14:43Z"
  name: wear-service
  namespace: app-space
  resourceVersion: "572"
  selfLink: /api/v1/namespaces/app-space/services/wear-service
  uid: 9ea810be-ac13-46ea-83cf-e86427af1bd3
spec:
  clusterIP: 10.105.109.103
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp-wear
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}