apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-03T18:14:43Z"
  name: video-service
  namespace: app-space
  resourceVersion: "586"
  selfLink: /api/v1/namespaces/app-space/services/video-service
  uid: fdb4870c-237f-4be8-bfef-24358376922d
spec:
  clusterIP: 10.102.61.41
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp-video
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}